[dev]
  port = 3000
  functions = "netlify/functions"
  functions-port= 3002
  publish = "public"


[template.environment]
 	# Environment variables needed
  APP_ID = "Your Intercom App Id"
  CLIENT_ID = "Your Intercom Oauth Client Id"
  CLIENT_SECRET = "Your Intercom Oauth Secret"